# Please do the following before coming to lab:

1. Watch the pre-class video on python (link: https://youtu.be/Ro_MScTDfU4?si=eKwFy99_ih1eUWUP
) and go through this "worksheet" (it's just examples with empty code cells for you to experiment)on numpy.
2. Complete the pre-class concept check based on the video and the worksheet.
3. Get your GitHub repository set up for lab 3 by 
    * Creating a new branch called `ca3` 
    * Putting the required lab files in this branch (this worksheet + the in-class worksheet when it is uploaded).

By the time you come to lab, you should be able to just open VSCode and get started with the in-class worksheet.


# Concept Check

In the video they created a chatbox, let's try to do that here. Follow these rules:
1. When you say "hi" or "hello", the bot should respond with "Hello! How can I help you today?"
2. When you say "bye" or "goodbye", the bot should respond with "Goodbye! Have a great day!"
3. For any other input, the bot should respond with "I'm sorry, I didn't understand that."


*This guide has been taken from the official documentation of NumPy, the goal is to only introduce the functions and topics important right now. If you want to, you can learn more at: https://numpy.org/doc/stable/user/absolute_beginners.html*

*Please watch the python introduction video before starting this worksheet (It's ungraded, so go nuts with the code).*

# Numpy

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

You will already have numpy installed through the requirements.txt file. You can import the library as follows:

```python
import numpy as np
```

Try it out in the cell below:

## How to read example code

You might see code snippets like this in the examples below:

```python
# Create a 1D array
>>> a = np.array([[0, 1, 2, 3],
...               [4, 5, 6, 7]])
>>> a.shape
(2, 4)
```
Text preceded by `>>>` or `...` is the input, so the code that you will put in your code cells. Everything else is the output that you will see when you run the code. Please note that `>>>` and `...` are not part of the code, and could cause an error if copied into the code cells. 

Try and run the above code in the cell below, you should get the output `(2, 4)`.

## Why NumPy?
Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types (for e.g. `l = [1, "A", 3, "B"]`), and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the data and the types of operations that need to be performed, other containers may be more appropriate; they can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

NumPy uses arrays as its basic data structure.

### What is an array?
In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

```python
[ 0, 1, 2, 3]
```
A 2D array would be like a table or matrix:

```python
[[ 0, 1, 2, 3 ],
 [ 4, 5, 6, 7 ],
 [ 8, 9,10,11 ]]
```
A 3D array would be like a cube of data, or perhaps like a stack of tables or matrices (imagine you stack pieces of paper each with a 2D array on it). In general, an array can have any number of dimensions, so the fundamental array class is called `ndarray`: representing an "N-dimensional array".

Arrays have some restrictions:
* All elements of the array must be of the same type of data.
* Once created, the total size of the array can’t change (unlike lists, where you can append elements).
* The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

For the remainder of this document, we will use the word “array” to refer to an instance of `ndarray`.

# Array fundamentals

One way to initialize an array is using a Python sequence, such as a list. For example:

```python
>>> a = np.array([1, 2, 3, 4, 5, 6])
>>> a
array([1, 2, 3, 4, 5, 6])
```

Elements of an array can be accesed using square brackets with the element index (starting from 0 for the first element), just like lists:

```python
>>> a[0]
1
```
Try creating an array and accessing its elements in the cell below (try accessing elements at different indices):

Also like the original list, arrays are mutable, meaning that the contents can be changed after the array is created (although the size of the array can’t be changed). For example:

```python
>>> a[3] = 10
>>> a
array([1,  2,  3,  10,  5,  6])
```
Two- and higher-dimensional arrays can be created using nested sequences (lists of lists, or lists of lists of lists, and so on). For example:

```python
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
>>> a
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
```
To access elements of a multi-dimensional array, you use a comma-separated list of indices (You cant do the same in lists, you have to use multiple square brackets to list all the indices). For example:

```python
>>> a[1, 2]
7
```
Try creating a 2D array and accessing its elements in the cell below (try accessing elements at different indices):

# Array attributes

Here we will cover how to access the properties or attributes of an array. We will cover `ndim`, `shape`, `size`, and `dtype`.

The number of dimensions of an array is contained in the `ndim` attribute.
```python
>>> a = np.array([[0, 1, 2, 3],
...               [4, 5, 6, 7]])
>>> a.ndim
2
```

The shape of an array is contained in the `shape` attribute. The shape is a tuple of integers giving the size of the array along each dimension (for e.g. the 2D array above with 2 rows and 4 columns will have a shape of `(2, 4)`).

```python
>>> a.shape
(2, 4)
>>> len(a.shape) == a.ndim
True
```
The length of this tuple is therefore the number of dimensions, and the values in the tuple give the size of the array along each dimension.

The total number of elements of the array is contained in the `size` attribute. It is equal to the product of the elements of the shape tuple.

```python
>>> a.size
8
>>> a.shape[0] * a.shape[1] == a.size
True
```
The data type of the elements in the array is contained in the `dtype` attribute. NumPy arrays contain elements all of the same type, and this type is specified by a special object called a `dtype` (data-type) object. Some common examples of data types are `int` (integer), `float` (floating-point number), and `bool` (Boolean: True or False).

```python
>>> a.dtype
dtype('int64')
```
Try creating an array and accessing its attributes in the cell below:

# Creating basic arrays
We can create arrays of different types using built in functions rather than using lists. Here are some examples:

To create an array which is filled with zeros, we can use the `np.zeros()` function. The argument to this function is a tuple specifying the shape of the array.

```python
>>> np.zeros((3, 4))
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
```

we can do the same with ones using the `np.ones()` function:

```python
>>> np.ones(2)
array([1., 1.])
>>> np.ones((2, 3))
array([[1., 1., 1.],
       [1., 1., 1.]])
```

We can even create an empty array using the `np.empty()` function. The values in the array will be whatever happens to already exist at that memory location, so they will be random and unpredictable.

```python
>>> np.empty(2)
array([3.14, 42.]) # random values
```
Why would you use `np.empty()` over `np.zeros()`? If later you are going to fill every element of the array with a new value anyway, then using `np.empty()` is slightly faster because it doesn’t have to first set all the values to zero.

You can create an array with a range of values using the `np.arange()` function. This is similar to the built-in Python function `range()`, but returns an array rather than a list. The arguments to this function are the start value (inclusive), the end value (exclusive), and the step size.

```python
>>> np.arange(10)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> np.arange(1, 10, 2)
array([1, 3, 5, 7, 9])
>>> np.arange(0, 1, 0.1)
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
```

Alternatively, you can create an array with a specified number of values evenly spaced between a start and end value using the `np.linspace()` function. The arguments to this function are the start value, the end value, and the number of values to generate.

```python
>>> np.linspace(0, 1, 5)
array([0.  , 0.25, 0.5 , 0.75, 1.  ])
>>> np.linspace(0, 10, 5)
array([ 0. ,  2.5,  5. ,  7.5, 10. ])
```
## Specifying the data type
The default data type of the elements in an array is `float` (floating-point number). However, you can specify a different data type using the `dtype` argument to the array creation functions. For example:

```python
>>> np.ones(3, dtype=int)
array([1, 1, 1]) # notice the lack of decimal points
>>> np.ones((2, 3), dtype=bool)
array([[ True,  True,  True],
       [ True,  True,  True]]) # Because 1 is interpreted as True and 0 as False
``` 

Try creating arrays of differnt types using the above functions in the cell below:

# Concept Check
Create a list of lists with 3 rows and 4 columns (think of it as a 3x4 matrix). Then convert this list of lists into a numpy array. Finally, extract the second column from this numpy array and print it.